
CREATE TABLE dbo.Persons (
  PersonID INT NOT NULL IDENTITY (1,1),
  FirstName NVARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL,
  CONSTRAINT PK_Persons PRIMARY KEY (PersonID)
)

INSERT INTO dbo.Persons (FirstName, LastName)
VALUES

('Melodi', 'Chagolla'),
('Denis', 'Widger'),
('Beverley', 'Greaney'),
('Starla', 'Penick'),
('Euna', 'Ferrer'),
('Orval', 'Gleeson'),
('Alvaro', 'Losh'),
('Chauncey', 'Aquilar'),
('Maybelle', 'Stonerock'),
('Jared', 'Gunderson'),
('Alia', 'Monarrez'),
('Winona', 'Avelar'),
('Mac', 'Locklin'),
('Alina', 'Wragg'),
('Jamar', 'Adamo'),
('Elna', 'Hodgson'),
('Genna', 'Salvaggio'),
('Lorraine', 'Ringdahl'),
('Margurite', 'Frampton'),
('Anna', 'Kyger'),
('Dominique', 'Dube'),
('Obdulia', 'Silvis'),
('Laticia', 'Brathwaite'),
('Tashina', 'Mobley'),
('Lesley', 'Kimball'),
('Jimmie', 'Patten'),
('Sol', 'Minarik'),
('Denita', 'Sawin'),
('Kristal', 'Deleon'),
('Flora', 'Bornstein'),
('Maurice', 'Cottman'),
('Keith', 'Perry'),
('Allison', 'Meszaros'),
('Asa', 'Sobota'),
('Kenna', 'Garabedian'),
('Floria', 'Haws'),
('Cody', 'Sayers'),
('Joane', 'Armand'),
('Dayna', 'Moak'),
('Sherlyn', 'Oakes'),
('Nathanael', 'Sprow'),
('Angelena', 'Morra'),
('Nicole', 'Helle'),
('Maribel', 'Rotunno'),
('Ambrose', 'Tobia'),
('Darlene', 'Biondo'),
('Jenise', 'Barnette'),
('Malka', 'Glance'),
('Shanta', 'Ohlson'),
('Kirsten', 'Wohl');
